// <auto-generated />
using System;
using LogiFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogiFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924061353_AddS4DeliveryDomain")]
    partial class AddS4DeliveryDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogiFlow.Domain.Entities.AgentWorkflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuditJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DispatchBatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Objective")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProposedPlanJson")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WorkflowKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DispatchBatchId");

                    b.HasIndex("WorkflowKey")
                        .IsUnique();

                    b.ToTable("AgentWorkflows", (string)null);
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.ApprovalDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("AgentWorkflowId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecidedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("RevisionsJson")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("AgentWorkflowId");

                    b.ToTable("ApprovalDecisions", (string)null);
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFragile")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpecialHandling")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("StorageZoneId")
                        .HasColumnType("uuid");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("VolumeM3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("StorageZoneId");

                    b.HasIndex("TrackingCode")
                        .IsUnique();

                    b.HasIndex("WarehouseId");

                    b.ToTable("Packages", null, t =>
                        {
                            t.HasCheckConstraint("CK_Packages_VolumeM3_Positive", "\"VolumeM3\" > 0");

                            t.HasCheckConstraint("CK_Packages_WeightKg_Positive", "\"WeightKg\" > 0");
                        });
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.ProofOfDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ReceivedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("RouteStopId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("SignatureImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("RouteStopId")
                        .IsUnique();

                    b.HasIndex("ShipmentId");

                    b.ToTable("ProofOfDeliveries", (string)null);
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.RouteStop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("AgentWorkflowId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DistanceFromPrevKm")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<DateTime>("Eta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<bool?>("OnTime")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StopKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("WindowEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("WindowStart")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("AgentWorkflowId", "Sequence")
                        .IsUnique();

                    b.ToTable("RouteStops", null, t =>
                        {
                            t.HasCheckConstraint("CK_RouteStops_DistanceFromPrevKm_NonNegative", "\"DistanceFromPrevKm\" >= 0");

                            t.HasCheckConstraint("CK_RouteStops_Sequence_Positive", "\"Sequence\" > 0");
                        });
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentWorkflowId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PlannedStartAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShipmentCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("TotalDistanceKm")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("TotalDurationMin")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AgentWorkflowId")
                        .IsUnique();

                    b.HasIndex("DriverId");

                    b.HasIndex("ShipmentCode")
                        .IsUnique();

                    b.HasIndex("VehicleId");

                    b.ToTable("Shipments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Shipments_TotalDistanceKm_NonNegative", "\"TotalDistanceKm\" >= 0");

                            t.HasCheckConstraint("CK_Shipments_TotalDurationMin_NonNegative", "\"TotalDurationMin\" >= 0");
                        });
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.StorageZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("OccupiedVolumeM3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("TotalVolumeM3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId", "Code")
                        .IsUnique();

                    b.ToTable("StorageZones", null, t =>
                        {
                            t.HasCheckConstraint("CK_StorageZones_OccupiedVolumeM3_Valid", "\"OccupiedVolumeM3\" >= 0 AND \"OccupiedVolumeM3\" <= \"TotalVolumeM3\"");

                            t.HasCheckConstraint("CK_StorageZones_TotalVolumeM3_Positive", "\"TotalVolumeM3\" > 0");
                        });
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.TrackingEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RouteStopId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RouteStopId");

                    b.HasIndex("ShipmentId", "OccurredAt");

                    b.ToTable("TrackingEvents", (string)null);
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("OccupiedVolumeM3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("TotalVolumeM3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Warehouses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Warehouses_OccupiedVolumeM3_Valid", "\"OccupiedVolumeM3\" >= 0 AND \"OccupiedVolumeM3\" <= \"TotalVolumeM3\"");

                            t.HasCheckConstraint("CK_Warehouses_TotalVolumeM3_Positive", "\"TotalVolumeM3\" > 0");
                        });
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.ApprovalDecision", b =>
                {
                    b.HasOne("LogiFlow.Domain.Entities.AgentWorkflow", "AgentWorkflow")
                        .WithMany("ApprovalDecisions")
                        .HasForeignKey("AgentWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentWorkflow");
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.Package", b =>
                {
                    b.HasOne("LogiFlow.Domain.Entities.StorageZone", "StorageZone")
                        .WithMany("Packages")
                        .HasForeignKey("StorageZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogiFlow.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("Packages")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StorageZone");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.ProofOfDelivery", b =>
                {
                    b.HasOne("LogiFlow.Domain.Entities.Shipment", "Shipment")
                        .WithMany("ProofOfDeliveries")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.RouteStop", b =>
                {
                    b.HasOne("LogiFlow.Domain.Entities.AgentWorkflow", "AgentWorkflow")
                        .WithMany("RouteStops")
                        .HasForeignKey("AgentWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentWorkflow");
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.Shipment", b =>
                {
                    b.HasOne("LogiFlow.Domain.Entities.AgentWorkflow", "AgentWorkflow")
                        .WithOne("Shipment")
                        .HasForeignKey("LogiFlow.Domain.Entities.Shipment", "AgentWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentWorkflow");
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.StorageZone", b =>
                {
                    b.HasOne("LogiFlow.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("StorageZones")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.TrackingEvent", b =>
                {
                    b.HasOne("LogiFlow.Domain.Entities.Shipment", "Shipment")
                        .WithMany("TrackingEvents")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.AgentWorkflow", b =>
                {
                    b.Navigation("ApprovalDecisions");

                    b.Navigation("RouteStops");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.Shipment", b =>
                {
                    b.Navigation("ProofOfDeliveries");

                    b.Navigation("TrackingEvents");
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.StorageZone", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.Warehouse", b =>
                {
                    b.Navigation("Packages");

                    b.Navigation("StorageZones");
                });
#pragma warning restore 612, 618
        }
    }
}
