// <auto-generated />
using System;
using LogiFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LogiFlow.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260923071434_AddS3DispatchBatches")]
    partial class AddS3DispatchBatches
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LogiFlow.Domain.Entities.DispatchBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MaxVolumeM3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("MaxWeightKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("DispatchBatches", null, t =>
                        {
                            t.HasCheckConstraint("CK_DispatchBatches_MaxVolumeM3_Positive", "\"MaxVolumeM3\" > 0");

                            t.HasCheckConstraint("CK_DispatchBatches_MaxWeightKg_Positive", "\"MaxWeightKg\" > 0");
                        });
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.DispatchBatchItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DispatchBatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("LoadSequence")
                        .HasColumnType("integer");

                    b.Property<Guid>("PackageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PackageId")
                        .IsUnique();

                    b.HasIndex("DispatchBatchId", "LoadSequence")
                        .IsUnique();

                    b.ToTable("DispatchBatchItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_DispatchBatchItems_LoadSequence_Positive", "\"LoadSequence\" > 0");
                        });
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFragile")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpecialHandling")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("StorageZoneId")
                        .HasColumnType("uuid");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("VolumeM3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("StorageZoneId");

                    b.HasIndex("TrackingCode")
                        .IsUnique();

                    b.HasIndex("WarehouseId");

                    b.ToTable("Packages", null, t =>
                        {
                            t.HasCheckConstraint("CK_Packages_VolumeM3_Positive", "\"VolumeM3\" > 0");

                            t.HasCheckConstraint("CK_Packages_WeightKg_Positive", "\"WeightKg\" > 0");
                        });
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.StorageZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("OccupiedVolumeM3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("TotalVolumeM3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId", "Code")
                        .IsUnique();

                    b.ToTable("StorageZones", null, t =>
                        {
                            t.HasCheckConstraint("CK_StorageZones_OccupiedVolumeM3_Valid", "\"OccupiedVolumeM3\" >= 0 AND \"OccupiedVolumeM3\" <= \"TotalVolumeM3\"");

                            t.HasCheckConstraint("CK_StorageZones_TotalVolumeM3_Positive", "\"TotalVolumeM3\" > 0");
                        });
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("OccupiedVolumeM3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("TotalVolumeM3")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Warehouses", null, t =>
                        {
                            t.HasCheckConstraint("CK_Warehouses_OccupiedVolumeM3_Valid", "\"OccupiedVolumeM3\" >= 0 AND \"OccupiedVolumeM3\" <= \"TotalVolumeM3\"");

                            t.HasCheckConstraint("CK_Warehouses_TotalVolumeM3_Positive", "\"TotalVolumeM3\" > 0");
                        });
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.DispatchBatch", b =>
                {
                    b.HasOne("LogiFlow.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("DispatchBatches")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.DispatchBatchItem", b =>
                {
                    b.HasOne("LogiFlow.Domain.Entities.DispatchBatch", "DispatchBatch")
                        .WithMany("Items")
                        .HasForeignKey("DispatchBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LogiFlow.Domain.Entities.Package", "Package")
                        .WithMany("DispatchBatchItems")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DispatchBatch");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.Package", b =>
                {
                    b.HasOne("LogiFlow.Domain.Entities.StorageZone", "StorageZone")
                        .WithMany("Packages")
                        .HasForeignKey("StorageZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LogiFlow.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("Packages")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("StorageZone");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.StorageZone", b =>
                {
                    b.HasOne("LogiFlow.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("StorageZones")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.DispatchBatch", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.Package", b =>
                {
                    b.Navigation("DispatchBatchItems");
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.StorageZone", b =>
                {
                    b.Navigation("Packages");
                });

            modelBuilder.Entity("LogiFlow.Domain.Entities.Warehouse", b =>
                {
                    b.Navigation("DispatchBatches");

                    b.Navigation("Packages");

                    b.Navigation("StorageZones");
                });
#pragma warning restore 612, 618
        }
    }
}
