import {
  type DispatchAgentValidationResponse,
  useRunDispatchAgentValidationMutation,
} from '../warehouseApi'
import { ApiMessage, userFacingApiError } from './ApiMessage'

export function AgentValidationPanel({ batchId }: { batchId: string }) {
  const [runValidation, { data, error, isLoading }] = useRunDispatchAgentValidationMutation()

  return (
    <section className="surface validation-panel agent-validation-panel" aria-label="Agentic AI validation">
      <p className="eyebrow">Internal agent service</p>
      <h2>Agentic AI validation</h2>
      <p>The backend sends the persisted batch to the internal validation agent. Deterministic backend rules remain the safety authority.</p>
      <button type="button" onClick={() => runValidation(batchId)} disabled={isLoading}>
        {isLoading ? 'Requesting agent explanation…' : 'Generate AI validation explanation'}
      </button>
      {error && <ApiMessage kind="error">{userFacingApiError(error, 'The agent validation request could not be completed.')}</ApiMessage>}
      {data && <AgentValidationOutput response={data} />}
    </section>
  )
}

function AgentValidationOutput({ response }: { response: DispatchAgentValidationResponse }) {
  const deterministicPass = response.deterministicResult === 'PASS'
  return (
    <div className="agent-result">
      <ApiMessage kind={deterministicPass ? 'success' : 'error'}>
        Deterministic backend decision: {response.deterministicResult}
      </ApiMessage>
      {!response.agentAvailable && <ApiMessage kind="info">{response.agentMessage}</ApiMessage>}
      {response.agentAvailable && !response.agentConsistent && <ApiMessage kind="error">{response.agentMessage}</ApiMessage>}
      {response.agentAvailable && response.agentConsistent && (
        <>
          <p><strong>Agent result:</strong> {response.agentResult}</p>
          {response.explanation && <blockquote className="agent-explanation">{response.explanation}</blockquote>}
          <p className="agent-source">
            {response.explanationSource === 'ollama'
              ? 'Explanation generated by the configured local Ollama model. It cannot change the decision.'
              : 'Ollama was unavailable, so the agent returned a deterministic operator explanation.'}
          </p>
          <ul className="validation-rules">
            {response.ruleResults.map((rule) => (
              <li className={rule.passed ? 'rule-pass' : 'rule-fail'} key={rule.rule}>
                <span>{rule.passed ? '✓' : '×'}</span>
                <strong>{formatRule(rule.rule)}:</strong> {rule.detail ?? (rule.passed ? 'Passed' : 'Failed')}
              </li>
            ))}
          </ul>
        </>
      )}
    </div>
  )
}

function formatRule(rule: string) {
  return rule.split('_').join(' ').replace(/\b\w/g, (letter: string) => letter.toUpperCase())
}
